# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
