# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0003_auto_20170104_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='deleted_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
