# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0004_auto_20170127_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='show_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 14, 29, 16, 565236)),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
