# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayerlistapp', '0005_auto_20170201_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='show_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
