# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0006_auto_20170206_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayerrequest',
            old_name='user',
            new_name='created_by',
        ),
    ]
