# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayerlistapp', '0007_auto_20170206_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_urgent_pr', models.PositiveSmallIntegerField(default=6)),
                ('num_normal_pr', models.PositiveSmallIntegerField(default=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='prayerlistapp.Profile'),
        ),
    ]
