# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0008_auto_20170206_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_normal_pr',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Number of simple prayer requests on today page'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_urgent_pr',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Number of urgent prayer requests on today page'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_createdby', to='prayerlistapp.Profile'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(related_name='usergroup_usersattached', to='prayerlistapp.Profile'),
        ),
    ]
