# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0009_auto_20170210_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='show_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
