# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0010_prayerrequest_show_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['show_count', '-created_date']},
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='read_date',
            field=models.DateTimeField(null=True),
        ),
    ]
