# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayerlistapp', '0011_auto_20170306_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['show_count', 'is_read', '-created_date']},
        ),
    ]
